In [62]:
import pandas as pd 

filmes = pd.read_csv("movies.csv")
filmes.columns = ["filmeId", "titulo", "generos"]
filmes = filmes.set_index("filmeId")
filmes.head()

,titulo,generos
filmeId,,
1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
2,Jumanji (1995),Adventure|Children|Fantasy
3,Grumpier Old Men (1995),Comedy|Romance
4,Waiting to Exhale (1995),Comedy|Drama|Romance
5,Father of the Bride Part II (1995),Comedy

In [3]:
notas = pd.read_csv("ratings.csv")
notas.columns = ["usuarioId", "filmeId", "nota", "momento"]
notas.head()

   usuarioId  filmeId  nota    momento
0          1        1   4.0  964982703
1          1        3   4.0  964981247
2          1        6   4.0  964982224
3          1       47   5.0  964983815
4          1       50   5.0  964982931

Primeira Tentiva de Recomandação: Heurística de total de votos

In [12]:
total_de_votos = notas["filmeId"].value_counts()
total_de_votos.head()

filmeId
356     329
318     317
296     307
593     279
2571    278
Name: count, dtype: int64

In [14]:
filmes['total_de_votos'] = total_de_votos
filmes.head()

,movieId,title,genres,total_de_votos
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,NaN
1,2,Jumanji (1995),Adventure|Children|Fantasy,215.0
2,3,Grumpier Old Men (1995),Comedy|Romance,110.0
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,52.0
4,5,Father of the Bride Part II (1995),Comedy,7.0

In [16]:
filmes.sort_values("total_de_votos", ascending=False).head(10)

,movieId,title,genres,total_de_votos
356,412,"Age of Innocence, The (1993)",Drama,329.0
318,360,I Love Trouble (1994),Action|Comedy,317.0
296,338,Virtuosity (1995),Action|Sci-Fi|Thriller,307.0
593,735,Cemetery Man (Dellamorte Dellamore) (1994),Horror,279.0
2571,3439,Teenage Mutant Ninja Turtles II: The Secret of...,Action|Children|Fantasy,278.0
260,300,Quiz Show (1994),Drama,251.0
480,548,Terminal Velocity (1994),Action|Mystery|Thriller,238.0
110,128,Jupiter's Wife (1994),Documentary,237.0
589,726,Last Dance (1996),Drama,224.0
527,616,"Aristocats, The (1970)",Animation|Children,220.0

In [20]:
notas_medias = notas.groupby("filmeId").mean()["nota"]
notas_medias.head()

filmeId
1    3.920930
2    3.431818
3    3.259615
4    2.357143
5    3.071429
Name: nota, dtype: float64

In [22]:
filmes["nota_media"] = notas_medias
filmes.sort_values("total_de_votos", ascending=False).head(10)

,movieId,title,genres,total_de_votos,nota_media
356,412,"Age of Innocence, The (1993)",Drama,329.0,4.164134
318,360,I Love Trouble (1994),Action|Comedy,317.0,4.429022
296,338,Virtuosity (1995),Action|Sci-Fi|Thriller,307.0,4.197068
593,735,Cemetery Man (Dellamorte Dellamore) (1994),Horror,279.0,4.161290
2571,3439,Teenage Mutant Ninja Turtles II: The Secret of...,Action|Children|Fantasy,278.0,4.192446
260,300,Quiz Show (1994),Drama,251.0,4.231076
480,548,Terminal Velocity (1994),Action|Mystery|Thriller,238.0,3.750000
110,128,Jupiter's Wife (1994),Documentary,237.0,4.031646
589,726,Last Dance (1996),Drama,224.0,3.970982
527,616,"Aristocats, The (1970)",Animation|Children,220.0,4.225000

Uma segunda Heurística: Nota média e filtrando votos

In [24]:
filmes.sort_values("nota_media", ascending=False).head(20)

,movieId,title,genres,total_de_votos,nota_media
4454,6577,Kickboxer 2: The Road Back (1991),Action|Drama,1.0,5.0
4495,6654,Atragon (Kaitei Gunkan) (1963),Adventure|Sci-Fi,1.0,5.0
633,805,"Time to Kill, A (1996)",Drama|Thriller,1.0,5.0
4788,7131,"Summer Place, A (1959)",Drama,1.0,5.0
3637,4992,Kate & Leopold (2001),Comedy|Romance,1.0,5.0
8911,135456,Ghost in the Shell: Stand Alone Complex - The ...,Action|Animation|Crime|Sci-Fi,1.0,5.0
6442,51925,Premonition (2007),Drama|Fantasy|Mystery|Thriller,2.0,5.0
4813,7171,Aileen: Life and Death of a Serial Killer (2003),Documentary,1.0,5.0
2512,3360,Hoosiers (a.k.a. Best Shot) (1986),Drama|Romance,1.0,5.0
4402,6477,"Song of Bernadette, The (1943)",Drama,1.0,5.0
5059,7930,"People Under the Stairs, The (1991)",Horror|Mystery|Thriller,1.0,5.0
495,573,"Ciao, Professore! (Io speriamo che me la cavo)...",Drama,1.0,5.0
496,574,Spanking the Monkey (1994),Comedy|Drama,1.0,5.0
5088,8016,"Getaway, The (1972)",Action|Crime|Drama|Thriller,1.0,5.0
7122,71129,Green Lantern: First Flight (2009),Action|Adventure|Animation|Fantasy|Sci-Fi,1.0,5.0
7096,70361,12 Rounds (2009),Action|Thriller,1.0,5.0
467,534,Shadowlands (1993),Drama|Romance,1.0,5.0
7815,92535,Louis C.K.: Live at the Beacon Theater (2011),Comedy,1.0,5.0
2824,3773,House Party (1990),Comedy,1.0,5.0
5241,8591,"Philadelphia Experiment, The (1984)",Adventure|Drama|Sci-Fi,1.0,5.0

In [26]:
filmes.query("total_de_votos >= 10").sort_values("nota_media", ascending=False).head(10)

,movieId,title,genres,total_de_votos,nota_media
1041,1353,"Mirror Has Two Faces, The (1996)",Comedy|Drama|Romance,11.0,4.590909
3451,4708,Marat/Sade (1966),Drama|Musical,11.0,4.545455
1178,1569,My Best Friend's Wedding (1997),Comedy|Romance,12.0,4.541667
1104,1437,"Cement Garden, The (1993)",Drama,20.0,4.475000
2360,3127,Holy Smoke (1999),Comedy|Drama,12.0,4.458333
1217,1616,"Peacemaker, The (1997)",Action|Thriller|War,15.0,4.433333
318,360,I Love Trouble (1994),Action|Comedy,317.0,4.429022
951,1252,Chinatown (1974),Crime|Film-Noir|Mystery|Thriller,14.0,4.392857
1927,2555,Baby Geniuses (1999),Comedy,10.0,4.350000
922,1221,"Godfather: Part II, The (1974)",Crime|Drama,27.0,4.333333

In [ ]:
filmes_com_mais_de_50_votos = filmes.query("total_de_votos >= 50")
filmes_com_mais_de_50_votos.sort_values("nota_media", ascending=False).head(10)

,movieId,title,genres,total_de_votos,nota_media
318,360,I Love Trouble (1994),Action|Comedy,317.0,4.429022
858,1129,Escape from New York (1981),Action|Adventure|Sci-Fi|Thriller,192.0,4.289062
2959,3967,Billy Elliot (2000),Drama,218.0,4.272936
1276,1693,Amistad (1997),Drama|Mystery,57.0,4.271930
750,984,"Pompatus of Love, The (1996)",Comedy|Drama,97.0,4.268041
904,1202,Withnail & I (1987),Comedy,84.0,4.261905
1221,1621,Soul Food (1997),Drama,129.0,4.259690
1213,1612,"Kiss Me, Guido (1997)",Comedy,126.0,4.250000
912,1211,"Wings of Desire (Himmel über Berlin, Der) (1987)",Drama|Fantasy|Romance,100.0,4.240000
50,55,Georgia (1995),Drama,204.0,4.237745

Considerando Preferencias

In [ ]:
eu_assisti = [1,2,34,37,50,70,110,150,500,550,600,6,560,670,700,720,850,900,920,1000, 1100,1200,1300,1400,1500,1600,1700,1800,1900,2000]
filmes.loc[eu_assisti]

,movieId,title,genres,total_de_votos,nota_media
1,2,Jumanji (1995),Adventure|Children|Fantasy,215.0,3.920930
2,3,Grumpier Old Men (1995),Comedy|Romance,110.0,3.431818
34,38,It Takes Two (1995),Children|Comedy,128.0,3.652344
37,41,Richard III (1995),Drama|War,NaN,NaN
50,55,Georgia (1995),Drama,204.0,4.237745
70,78,"Crossing Guard, The (1995)",Action|Crime|Drama|Thriller,55.0,3.509091
110,128,Jupiter's Wife (1994),Documentary,237.0,4.031646
150,178,Love & Human Remains (1993),Comedy|Drama,201.0,3.845771
500,580,Princess Caraboo (1994),Drama,144.0,3.388889
550,656,Eddie (1996),Comedy,5.0,3.400000
600,747,"Stupids, The (1996)",Comedy,1.0,4.000000

In [71]:
filmes["nota_media"] = notas.groupby("filmeId").mean()["nota"]
aventura_infantil_e_fantasia = filmes_com_mais_de_50_votos.query("genres=='Adventure|Children|Fantasy'")
aventura_infantil_e_fantasia.drop(eu_assisti, errors='ignore').sort_values("nota_media", ascending = False).head(10)

,movieId,title,genres,total_de_votos,nota_media
1617,2161,"NeverEnding Story, The (1984)",Adventure|Children|Fantasy,97.0,4.061856
8641,119655,Seventh Son (2014),Adventure|Children|Fantasy,57.0,3.771930